### ISSUE TITLE
Client.connect panics if connection is refused

### ISSUE THREAD

**Issue by paul-hansen** [naia-lib/naia#91]
## What happens

If you connect to an address that doesn't have a server running, the client panics when calling [`client.connect`](https://docs.rs/naia-client/0.12.0/naia_client/struct.Client.html#method.connect).

```
thread 'main' panicked at 'Could not send request, original error: reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(127.0.0.1)), port: Some(14191), path: "/rtc_session", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." })) }', C:\Users\Paul\.cargo\registry\src\github.com-1ecc6299db9ec823\webrtc-unreliable-client-0.1.2\src\socket.rs:109:17
```
This can be seen by running any of the client examples without a server running.

## What I would like to happen

It would be nice if [`client.connect`](https://docs.rs/naia-client/0.12.0/naia_client/struct.Client.html#method.connect) returned a result with different errors (Usually an enum) for the different failure states, allowing me to show an error message to users and allow them to retry without leaving my app.

**Comment by paul-hansen** [comment]
I would be willing to help with this but it appears that [`RTCSocket::connect`](https://github.com/naia-lib/naia/blob/dfca4ec7b58a74353f0e7c72e56f0e8517768a14/socket/client/src/backends/native/socket.rs#L61) should probably be changed to return a result. It looks like that is defined in a repo that hasn't been made public? I could be missing something there.

**Comment by connorcarpenter** [comment]
Thank you for reporting this :)
Yeah this is already fixed in https://github.com/naia-lib/naia/pull/89, hope to release soon :+1:

**Comment by paul-hansen** [comment]
Awesome! That's great to hear ❤️

**Comment by paul-hansen** [comment]
I checked out the latest commit 37e2fe42873f734ec61589fff128bfc40feb4611 in the release-0.13.0 branch to try it out and I'm still seeing the same panic. Running the basic miniquad client demo without a server running still panics on [this line](https://github.com/naia-lib/naia/blob/37e2fe42873f734ec61589fff128bfc40feb4611/demos/basic/client/app/src/app.rs#L38) and I don't see a result added to [the connect method](https://github.com/naia-lib/naia/blob/37e2fe42873f734ec61589fff128bfc40feb4611/client/src/client.rs#L78).

I'm probably missing something obvious, sorry in advance lol.

**Comment by connorcarpenter** [comment]
Yeah I have a couple fixes in https://github.com/naia-lib/webrtc-unreliable-client too that are necessary to avoid that error. Will update that as well with the next release :+1: Thanks for looking into it!
